namespace Microsoft.CodeAnalysis;

public enum SymbolDisplayPartKind
{
	AliasName,
	AssemblyName,
	ClassName,
	DelegateName,
	EnumName,
	ErrorTypeName,
	EventName,
	FieldName,
	InterfaceName,
	Keyword,
	LabelName,
	LineBreak,
	NumericLiteral,
	StringLiteral,
	LocalName,
	MethodName,
	ModuleName,
	NamespaceName,
	Operator,
	ParameterName,
	PropertyName,
	Punctuation,
	Space,
	StructName,
	AnonymousTypeIndicator,
	Text,
	TypeParameterName,
	RangeVariableName,
	EnumMemberName,
	ExtensionMethodName,
	ConstantName,
	RecordClassName,
	RecordStructName
}
