using System;

namespace Microsoft.CodeAnalysis.CSharp.Symbols;

[Flags]
internal enum CompletionPart
{
	None = 0,
	Attributes = 1,
	ReturnTypeAttributes = 2,
	Parameters = 4,
	Type = 8,
	StartBaseType = 0x10,
	FinishBaseType = 0x20,
	StartInterfaces = 0x40,
	FinishInterfaces = 0x80,
	EnumUnderlyingType = 0x100,
	TypeArguments = 0x200,
	TypeParameters = 0x400,
	Members = 0x800,
	TypeMembers = 0x1000,
	SynthesizedExplicitImplementations = 0x2000,
	StartMemberChecks = 0x4000,
	FinishMemberChecks = 0x8000,
	MembersCompletedChecksStarted = 0x10000,
	MembersCompleted = 0x20000,
	All = Attributes | ReturnTypeAttributes | Parameters | Type | StartBaseType | FinishBaseType | StartInterfaces | FinishInterfaces | EnumUnderlyingType | TypeArguments | TypeParameters | Members | TypeMembers | SynthesizedExplicitImplementations | StartMemberChecks | FinishMemberChecks | MembersCompletedChecksStarted | MembersCompleted,
	NamedTypeSymbolWithLocationAll = 0xFFF1,
	NamedTypeSymbolAll = 0x3FFF1,
	StartValidatingImports = StartBaseType,
	FinishValidatingImports = FinishBaseType,
	ImportsAll = 0x30,
	NameToMembersMap = Members,
	NamespaceSymbolAll = 0x20800,
	FixedSize = Members,
	ConstantValue = TypeMembers,
	FieldSymbolAll = 0x1809,
	StartAsyncMethodChecks = Members,
	FinishAsyncMethodChecks = TypeMembers,
	StartMethodChecks = SynthesizedExplicitImplementations,
	FinishMethodChecks = StartMemberChecks,
	MethodSymbolAll = 0x7C0F,
	StartDefaultSyntaxValue = Members,
	EndDefaultSyntaxValue = TypeMembers,
	EndDefaultSyntaxValueDiagnostics = SynthesizedExplicitImplementations,
	StartMiscValidation = StartMemberChecks,
	EndMiscValidation = FinishMemberChecks,
	ComplexParameterSymbolAll = 0xF801,
	TypeParameterConstraints = Members,
	TypeParameterSymbolAll = 0x801,
	StartPropertyEnsureSignature = StartBaseType,
	FinishPropertyEnsureSignature = FinishBaseType,
	StartPropertyParameters = StartInterfaces,
	FinishPropertyParameters = FinishInterfaces,
	StartPropertyType = EnumUnderlyingType,
	FinishPropertyType = TypeArguments,
	PropertySymbolAll = 0x3F1,
	AliasTarget = StartBaseType,
	StartAttributeChecks = StartBaseType,
	FinishAttributeChecks = FinishBaseType,
	Module = StartInterfaces,
	StartValidatingAddedModules = EnumUnderlyingType,
	FinishValidatingAddedModules = TypeArguments,
	AssemblySymbolAll = 0x371,
	StartValidatingReferencedAssemblies = StartBaseType,
	FinishValidatingReferencedAssemblies = FinishBaseType
}
