namespace Microsoft.CodeAnalysis.Collections.Internal;

internal enum ExceptionResource
{
	ArgumentOutOfRange_IndexMustBeLessOrEqual,
	ArgumentOutOfRange_IndexMustBeLess,
	ArgumentOutOfRange_Count,
	Arg_ArrayPlusOffTooSmall,
	Arg_RankMultiDimNotSupported,
	Arg_NonZeroLowerBound,
	ArgumentOutOfRange_ListInsert,
	ArgumentOutOfRange_NeedNonNegNum,
	ArgumentOutOfRange_SmallCapacity,
	Argument_InvalidOffLen,
	ArgumentOutOfRange_BiggerThanCollection,
	NotSupported_KeyCollectionSet,
	NotSupported_ValueCollectionSet,
	InvalidOperation_IComparerFailed
}
