typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef signed int s32;
typedef unsigned long usize;
#define NOMCLK 125000000u
#define I2C_SLAVE 0x0703u
#define ESP32_ADDR 0x40u
static const char devi2c[] = "/dev/i2c-0";
static inline long sc_open(const char *p,long flags,long mode){register long r0 asm("r0")=(long)p;register long r1 asm("r1")=flags;register long r2 asm("r2")=mode;register long r7 asm("r7")=5;asm volatile("svc 0":"+r"(r0):"r"(r1),"r"(r2),"r"(r7):"memory","cc");return r0;}
static inline long sc_close(long fd){register long r0 asm("r0")=fd;register long r7 asm("r7")=6;asm volatile("svc 0":"+r"(r0):"r"(r7):"memory","cc");return r0;}
static inline long sc_write(long fd,const void *buf,long len){register long r0 asm("r0")=fd;register long r1 asm("r1")=(long)buf;register long r2 asm("r2")=len;register long r7 asm("r7")=4;asm volatile("svc 0":"+r"(r0):"r"(r1),"r"(r2),"r"(r7):"memory","cc");return r0;}
static inline long sc_ioctl(long fd,long req,void *arg){register long r0 asm("r0")=fd;register long r1 asm("r1")=req;register long r2 asm("r2")=(long)arg;register long r7 asm("r7")=54;asm volatile("svc 0":"+r"(r0):"r"(r1),"r"(r2),"r"(r7):"memory","cc");return r0;}
static inline long sc_socket(long domain,long type,long protocol){register long r0 asm("r0")=domain;register long r1 asm("r1")=type;register long r2 asm("r2")=protocol;register long r7 asm("r7")=281;asm volatile("svc 0":"+r"(r0):"r"(r1),"r"(r2),"r"(r7):"memory","cc");return r0;}
static inline long sc_sendto(long fd,const void *buf,long len,long flags,const void *dst,long dstlen){register long r0 asm("r0")=fd;register long r1 asm("r1")=(long)buf;register long r2 asm("r2")=len;register long r3 asm("r3")=flags;register long r4 asm("r4")=(long)dst;register long r5 asm("r5")=dstlen;register long r7 asm("r7")=290;asm volatile("svc 0":"+r"(r0):"r"(r1),"r"(r2),"r"(r3),"r"(r4),"r"(r5),"r"(r7):"memory","cc");return r0;}
static inline long sc_setsockopt(long fd,long level,long opt,const void *val,long len){register long r0 asm("r0")=fd;register long r1 asm("r1")=level;register long r2 asm("r2")=opt;register long r3 asm("r3")=(long)val;register long r4 asm("r4")=len;register long r7 asm("r7")=294;asm volatile("svc 0":"+r"(r0):"r"(r1),"r"(r2),"r"(r3),"r"(r4),"r"(r7):"memory","cc");return r0;}
static inline u32 load_word_v8(const void *p){u32 v;asm volatile("ldr %0, [%1]":"=r"(v):"r"(p):"memory");return v;}
static void put_u16le(u8 *p,u16 v){p[0]=(u8)v;p[1]=(u8)(v>>8);}
static void put_u32le(u8 *p,u32 v){p[0]=(u8)v;p[1]=(u8)(v>>8);p[2]=(u8)(v>>16);p[3]=(u8)(v>>24);}
static u8 crc8_atm(const u8 *p,u32 n){u8 crc=0;for(u32 i=0;i<n;i++){crc^=p[i];for(u32 b=0;b<8;b++)crc=(u8)((crc&0x80u)?((crc<<1)^0x07u):(crc<<1));}return crc;}
static void udp_send_once(const u8 *pkt){long s=sc_socket(2,2,0);if(s<0)return;s32 one=1;if(sc_setsockopt(s,1,6,&one,4)>=0){u8 dst[16];for(u32 i=0;i<16;i++)dst[i]=0;dst[0]=2;dst[2]=0x2e;dst[3]=0xe7;dst[4]=dst[5]=dst[6]=dst[7]=0xff;(void)sc_sendto(s,pkt,32,0,dst,16);}(void)sc_close(s);}
static void i2c_send_once(u8 *pkt){long fd=sc_open(devi2c,2,0);if(fd<0)return;if(sc_ioctl(fd,I2C_SLAVE,(void*)(usize)ESP32_ADDR)>=0)(void)sc_write(fd,pkt,32);(void)sc_close(fd);}
__attribute__((used,visibility("default"))) void telemetry_send_v8(void *gps_sp_void){u8 *gps_sp=(u8*)gps_sp_void;volatile u32 *gps_used_ptr=(volatile u32*)(usize)load_word_v8(gps_sp+0x04);volatile u32 *gps_sw_ptr=(volatile u32*)(usize)load_word_v8(gps_sp+0x0c);volatile u32 *pps_raw_ptr=(volatile u32*)(usize)load_word_v8(gps_sp+0x10);volatile u32 *pps_seq_ptr=(volatile u32*)(usize)load_word_v8(gps_sp+0x18);u32 age=load_word_v8(gps_sp+0x20),acq=load_word_v8(gps_sp+0x28),used=load_word_v8((const void*)gps_used_ptr),sw=load_word_v8((const void*)gps_sw_ptr),raw=load_word_v8((const void*)pps_raw_ptr),pps=load_word_v8((const void*)pps_seq_ptr),hw=load_word_v8((const void*)(gps_used_ptr-1));u32 locked=(sw&2u)?1u:0u,hold=(sw&4u)?1u:0u,raw_ok=(raw>=124000000u&&raw<=126000000u)?1u:0u,state;if(!(hw&1u))state=1u;else if(locked&&hold)state=4u;else if(locked)state=3u;else if(raw_ok)state=2u;else state=5u;u32 flags=1u;if(hw&1u)flags|=2u;if(hw&2u)flags|=4u;if(hw&4u)flags|=8u;if(locked)flags|=16u;if(hold)flags|=32u;if(locked&&used)flags|=64u;if(used)flags|=128u;u8 pkt[32];for(u32 i=0;i<32;i++)pkt[i]=0;pkt[0]=0x07u;pkt[1]=(u8)pps;pkt[2]=0x5Au;pkt[3]=0x02u;pkt[4]=(u8)state;pkt[5]=(u8)flags;pkt[6]=(u8)((locked&&used)?0x0Fu:0u);pkt[7]=(u8)acq;put_u32le(pkt+8,pps);put_u32le(pkt+12,raw);put_u32le(pkt+16,used);s32 err_hz=used?((s32)used-(s32)NOMCLK):0;put_u32le(pkt+20,(u32)err_hz);put_u32le(pkt+24,(u32)(err_hz*8));put_u16le(pkt+28,(u16)((age>65535u)?65535u:age));pkt[30]=(u8)(0x20u|(raw_ok?0x01u:0u)|((age==0u)?0x08u:0u));pkt[31]=crc8_atm(pkt,31);udp_send_once(pkt);i2c_send_once(pkt);}
