using System;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Roslyn.Utilities;

internal static class GeneratedCodeUtilities
{
	private static readonly string[] s_autoGeneratedStrings = new string[2] { "<autogenerated", "<auto-generated" };

	internal static bool IsGeneratedSymbolWithGeneratedCodeAttribute(ISymbol symbol, INamedTypeSymbol generatedCodeAttribute)
	{
		if (symbol.Kind != SymbolKind.Namespace)
		{
			if (symbol.DeclaringSyntaxReferences.Length > 1)
			{
				return false;
			}
			foreach (AttributeData attribute in symbol.GetAttributes())
			{
				if (generatedCodeAttribute.Equals(attribute.AttributeClass))
				{
					return true;
				}
			}
		}
		if (symbol.ContainingSymbol != null)
		{
			return IsGeneratedSymbolWithGeneratedCodeAttribute(symbol.ContainingSymbol, generatedCodeAttribute);
		}
		return false;
	}

	internal static bool IsGeneratedCode(SyntaxTree tree, Func<SyntaxTrivia, bool> isComment, CancellationToken cancellationToken)
	{
		if (!IsGeneratedCodeFile(tree.FilePath))
		{
			return BeginsWithAutoGeneratedComment(tree, isComment, cancellationToken);
		}
		return true;
	}

	internal static bool IsGeneratedCode(string? filePath, SyntaxNode root, Func<SyntaxTrivia, bool> isComment)
	{
		if (!IsGeneratedCodeFile(filePath))
		{
			return BeginsWithAutoGeneratedComment(root, isComment);
		}
		return true;
	}

	private static bool IsGeneratedCodeFile([NotNullWhen(true)] string? filePath)
	{
		if (!RoslynString.IsNullOrEmpty(filePath))
		{
			string fileName = PathUtilities.GetFileName(filePath);
			if (fileName.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase))
			{
				return true;
			}
			if (!string.IsNullOrEmpty(PathUtilities.GetExtension(fileName)))
			{
				string fileName2 = PathUtilities.GetFileName(filePath, includeExtension: false);
				if (fileName2.EndsWith(".designer", StringComparison.OrdinalIgnoreCase) || fileName2.EndsWith(".generated", StringComparison.OrdinalIgnoreCase) || fileName2.EndsWith(".g", StringComparison.OrdinalIgnoreCase) || fileName2.EndsWith(".g.i", StringComparison.OrdinalIgnoreCase))
				{
					return true;
				}
			}
		}
		return false;
	}

	private static bool BeginsWithAutoGeneratedComment(SyntaxNode root, Func<SyntaxTrivia, bool> isComment)
	{
		if (root.HasLeadingTrivia)
		{
			foreach (SyntaxTrivia leadingTrivium in root.GetLeadingTrivia())
			{
				if (!isComment(leadingTrivium))
				{
					continue;
				}
				string text = leadingTrivium.ToString();
				string[] array = s_autoGeneratedStrings;
				foreach (string value in array)
				{
					if (text.Contains(value))
					{
						return true;
					}
				}
			}
		}
		return false;
	}

	private static bool BeginsWithAutoGeneratedComment(SyntaxTree tree, Func<SyntaxTrivia, bool> isComment, CancellationToken cancellationToken)
	{
		SyntaxNode root = tree.GetRoot(cancellationToken);
		if (root.HasLeadingTrivia)
		{
			foreach (SyntaxTrivia leadingTrivium in root.GetLeadingTrivia())
			{
				if (!isComment(leadingTrivium))
				{
					continue;
				}
				string text = leadingTrivium.ToString();
				string[] array = s_autoGeneratedStrings;
				foreach (string value in array)
				{
					if (text.Contains(value))
					{
						return true;
					}
				}
			}
		}
		return false;
	}

	internal static GeneratedKind GetGeneratedCodeKindFromOptions(ImmutableDictionary<string, string> options)
	{
		if (options.TryGetValue("generated_code", out string value) && bool.TryParse(value, out var result))
		{
			if (!result)
			{
				return GeneratedKind.NotGenerated;
			}
			return GeneratedKind.MarkedGenerated;
		}
		return GeneratedKind.Unknown;
	}

	internal static GeneratedKind GetGeneratedCodeKindFromOptions(AnalyzerConfigOptions options)
	{
		if (options.TryGetValue("generated_code", out string value) && bool.TryParse(value, out var result))
		{
			if (!result)
			{
				return GeneratedKind.NotGenerated;
			}
			return GeneratedKind.MarkedGenerated;
		}
		return GeneratedKind.Unknown;
	}

	internal static bool? ToNullable(this GeneratedKind kind)
	{
		return kind switch
		{
			GeneratedKind.MarkedGenerated => true, 
			GeneratedKind.NotGenerated => false, 
			GeneratedKind.Unknown => null, 
			_ => throw ExceptionUtilities.UnexpectedValue(kind), 
		};
	}
}
