using System.Collections.Generic;
using System.Collections.Immutable;
using System.ComponentModel;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Microsoft.CodeAnalysis.CSharp;

public sealed class CSharpGeneratorDriver : GeneratorDriver
{
	internal override CommonMessageProvider MessageProvider => Microsoft.CodeAnalysis.CSharp.MessageProvider.Instance;

	internal override string SourceExtension => ".cs";

	internal override string EmbeddedAttributeDefinition => "// <auto-generated/>\r\nnamespace Microsoft.CodeAnalysis\r\n{\r\n    internal sealed partial class EmbeddedAttribute : global::System.Attribute\r\n    {\r\n    }\r\n}";

	internal override ISyntaxHelper SyntaxHelper => CSharpSyntaxHelper.Instance;

	internal CSharpGeneratorDriver(CSharpParseOptions parseOptions, ImmutableArray<ISourceGenerator> generators, AnalyzerConfigOptionsProvider optionsProvider, ImmutableArray<AdditionalText> additionalTexts, GeneratorDriverOptions driverOptions)
		: base(parseOptions, generators, optionsProvider, additionalTexts, driverOptions)
	{
	}

	private CSharpGeneratorDriver(GeneratorDriverState state)
		: base(state)
	{
	}

	public static CSharpGeneratorDriver Create(params ISourceGenerator[] generators)
	{
		return Create(generators, null, null, null, default(GeneratorDriverOptions));
	}

	public static CSharpGeneratorDriver Create(params IIncrementalGenerator[] incrementalGenerators)
	{
		return Create(incrementalGenerators.Select(GeneratorExtensions.AsSourceGenerator));
	}

	public static CSharpGeneratorDriver Create(IEnumerable<ISourceGenerator> generators, IEnumerable<AdditionalText>? additionalTexts = null, CSharpParseOptions? parseOptions = null, AnalyzerConfigOptionsProvider? optionsProvider = null, GeneratorDriverOptions driverOptions = default(GeneratorDriverOptions))
	{
		return new CSharpGeneratorDriver(parseOptions ?? CSharpParseOptions.Default, generators.ToImmutableArray(), optionsProvider ?? CompilerAnalyzerConfigOptionsProvider.Empty, additionalTexts.AsImmutableOrEmpty(), driverOptions);
	}

	[EditorBrowsable(EditorBrowsableState.Never)]
	public static CSharpGeneratorDriver Create(IEnumerable<ISourceGenerator> generators, IEnumerable<AdditionalText>? additionalTexts, CSharpParseOptions? parseOptions, AnalyzerConfigOptionsProvider? optionsProvider)
	{
		return Create(generators, additionalTexts, parseOptions, optionsProvider, default(GeneratorDriverOptions));
	}

	internal override SyntaxTree ParseGeneratedSourceText(GeneratedSourceText input, string fileName, CancellationToken cancellationToken)
	{
		return CSharpSyntaxTree.ParseTextLazy(input.Text, (CSharpParseOptions)_state.ParseOptions, fileName);
	}

	internal override GeneratorDriver FromState(GeneratorDriverState state)
	{
		return new CSharpGeneratorDriver(state);
	}
}
