namespace WindowsFirewallHelper;

public enum InternetControlMessageKnownTypesV6 : byte
{
	DestinationUnreachable = 1,
	PacketTooBig = 2,
	TimeExceeded = 3,
	ParameterProblem = 4,
	EchoRequest = 128,
	EchoReply = 129,
	MulticastListenerQuery = 130,
	MulticastListenerReport = 131,
	MulticastListenerDone = 132,
	RouterSolicitation = 133,
	RouterAdvertisement = 134,
	NeighborSolicitation = 135,
	NeighborAdvertisement = 136,
	Redirect = 137,
	RouterRenumbering = 138,
	ICMPNodeInformationQuery = 139,
	ICMPNodeInformationResponse = 140,
	InverseNeighborDiscoverySolicitation = 141,
	InverseNeighborDiscoveryAdvertisement = 142,
	MulticastListenerReportVersion2 = 143,
	HomeAgentAddressDiscoveryRequest = 144,
	HomeAgentAddressDiscoveryReply = 145,
	MobilePrefixSolicitation = 146,
	MobilePrefixAdvertisement = 147,
	CertificationPathSolicitation = 148,
	CertificationPathAdvertisement = 149,
	MulticastRouterAdvertisement = 151,
	MulticastRouterSolicitation = 152,
	MulticastRouterTermination = 153,
	FMIPv6Messages = 154,
	RPLControl = 155,
	ILNPv6LocatorUpdate = 156,
	DuplicateAddressRequest = 157,
	DuplicateAddressConfirmation = 158,
	MPLControl = 159
}
